FROM registry.access.redhat.com/ubi9/nodejs-16:1 as web-builder

WORKDIR /opt/app-root

COPY --chown=1001:0 Makefile Makefile
COPY --chown=1001:0 .mk/shortcuts.mk .mk/shortcuts.mk
COPY --chown=1001:0 web/package.json web/package.json
COPY --chown=1001:0 web/package-lock.json web/package-lock.json
COPY --chown=1001:0 .git .git
COPY --chown=1001:0 web web
COPY --chown=1001:0 mocks mocks
USER 1001

RUN NPM_INSTALL=ci make install-frontend

RUN make fmt-frontend build-frontend-standalone

FROM docker.io/library/golang:1.19 as go-builder

WORKDIR /opt/app-root

COPY .git .git
COPY go.mod go.mod
COPY go.sum go.sum
COPY vendor/ vendor/
COPY Makefile Makefile
COPY .mk/shortcuts.mk .mk/shortcuts.mk
COPY cmd/ cmd/
COPY pkg/ pkg/

RUN make build-backend

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.1

COPY --from=web-builder /opt/app-root/web/dist ./web/dist
COPY --from=go-builder /opt/app-root/plugin-backend ./

ENTRYPOINT ["./plugin-backend"]
